# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: InitializableImmutableAdminUpgradeabilityProxy
    address:
    - 0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2
    handler: src/EventHandlers.ts
    events:
    - event: BackUnbacked(address indexed reserve, address indexed backer, uint256 amount, uint256 fee)
    - event: Borrow(address indexed reserve, address user, address indexed onBehalfOf, uint256 amount, uint8 interestRateMode, uint256 borrowRate, uint16 indexed referralCode)
    - event: DeficitCovered(address indexed reserve, address caller, uint256 amountCovered)
    - event: DeficitCreated(address indexed user, address indexed debtAsset, uint256 amountCreated)
    - event: FlashLoan(address indexed target, address initiator, address indexed asset, uint256 amount, uint8 interestRateMode, uint256 premium, uint16 indexed referralCode)
    - event: IsolationModeTotalDebtUpdated(address indexed asset, uint256 totalDebt)
    - event: LiquidationCall(address indexed collateralAsset, address indexed debtAsset, address indexed user, uint256 debtToCover, uint256 liquidatedCollateralAmount, address liquidator, bool receiveAToken)
    - event: MintUnbacked(address indexed reserve, address user, address indexed onBehalfOf, uint256 amount, uint16 indexed referralCode)
    - event: MintedToTreasury(address indexed reserve, uint256 amountMinted)
    - event: Repay(address indexed reserve, address indexed user, address indexed repayer, uint256 amount, bool useATokens)
    - event: ReserveDataUpdated(address indexed reserve, uint256 liquidityRate, uint256 stableBorrowRate, uint256 variableBorrowRate, uint256 liquidityIndex, uint256 variableBorrowIndex)
    - event: ReserveUsedAsCollateralDisabled(address indexed reserve, address indexed user)
    - event: ReserveUsedAsCollateralEnabled(address indexed reserve, address indexed user)
    - event: Supply(address indexed reserve, address user, address indexed onBehalfOf, uint256 amount, uint16 indexed referralCode)
    - event: Upgraded(address indexed implementation)
    - event: UserEModeSet(address indexed user, uint8 categoryId)
    - event: Withdraw(address indexed reserve, address indexed user, address indexed to, uint256 amount)
